---
# file: tasks/htpasswd.yml

- name: Set up htpasswd users for vhosts
  htpasswd: path=/home/www-data/htpasswd/{{ item.0.domain }} name={{ item.1.name }} password={{ item.1.password }}
  with_subelements:
    - '{{ apache_vhosts }}'
    - htpasswd
  when: item.1|default([]) != []

- name: Set up htaccess file for vhosts
  template: src=templates/auth_htaccess.j2 dest=/home/www-data/{{ item.0.domain }}/.htaccess owner=www-data group=www-data mode=0644 
  with_subelements:
    - '{{ apache_vhosts }}'
    - htpasswd
  when: item.1|default([]) != []

- name: Remove htpasswd users for vhosts
  file: path=/home/www-data/htpasswd/{{ item.domain }} state=absent
  with_items: '{{ apache_vhosts }}'
  when: item.htpasswd|default([]) == []

- name: Remove htaccess file for vhosts
  file: path=/home/www-data/{{ item.domain }}/.htaccess state=absent
  with_items: '{{ apache_vhosts }}'
  when: item.htpasswd|default([]) == []
