---
# file: tasks/virtual-host-update.yml

- name: Update apache vhosts
  shell:
    sudo nine-manage-vhosts virtual-host update {{ item.0.domain }} --webroot={{ item.0.documentroot }} --template={{ item.0.template | default ('default') }}
  notify: Restart Apache
  with_together:
    - '{{ apache_vhosts }}'
    - '{{ apache_vhost_conf.results }}'
  when: item.1.stat.exists == True and item.0.vhost_status == 2 and item.0.template != 'default_letsencrypt_https'

- name: Update apache vhosts with intended Letsencrypt SSL templates
  shell:
    sudo nine-manage-vhosts virtual-host update {{ item.0.domain }} --webroot={{ item.0.documentroot }} --template=default
  notify: Restart Apache
  with_together:
    - '{{ apache_vhosts }}'
    - '{{ apache_vhost_conf.results }}'
  when: item.1.stat.exists == True and item.0.vhost_status == 2 and item.0.template == 'default_letsencrypt_https'

- name: Create Letsencrypt SSL certificates for existing vhosts
  shell:
    sudo nine-manage-vhosts certificate create --virtual-host={{ item.0.domain }}
  notify: Restart Apache
  with_together:
    - '{{ apache_vhosts }}'
    - '{{ apache_vhost_conf.results }}'
  when: item.1.stat.exists == True and item.0.vhost_status == 2 and item.0.template == 'default_letsencrypt_https'

- name: Update existing apache vhosts with their new Letsencrypt SSL Template
  shell:
    sudo nine-manage-vhosts virtual-host update {{ item.0.domain }} --webroot={{ item.0.documentroot }} --template={{ item.0.template | default ('default') }}
  notify: Restart Apache
  with_together:
    - '{{ apache_vhosts }}'
    - '{{ apache_vhost_conf.results }}'
  when: item.1.stat.exists == True and item.0.vhost_status == 2 and item.0.template == 'default_letsencrypt_https'
