---
# file: tasks/virtual-host-create.yml

- name: Create apache vhosts
  shell:
    sudo nine-manage-vhosts virtual-host create {{ item.0.domain }} --webroot={{ item.0.documentroot }} --template={{ item.0.template | default ('default') }}
  notify: Restart Apache
  with_together:
    - apache_vhosts
    - apache_vhost_conf.results
  when: item.1.stat.exists != True and item.0.vhost_status == 1